### ISSUE TITLE
Fix /health endpoint on kship 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/kship#6]
- update the kship health endpoint to actually reflect health (it just says true right now) from the accurator/health,  then the chart needs to be updated to reflect this
- need investigate why the health is not reporting accurately
- will include updating the helm chart

**Comment by Buwujiu** [comment]
note: Kship helm chart is updated in this PR: https://github.com/icgc-argo/charts/pull/116

**Comment by rosibaj** [comment]
Waiting on network policy update from @henro001

**Comment by henro001** [comment]
@rosibaj done for both dev and qa

**Comment by Buwujiu** [comment]
PR for adding allowing kship to kafka: https://github.com/OICR/argo-infra/pull/342

**Comment by Buwujiu** [comment]
@rosibaj @blabadi Kship is deployed to RDPC dev and qa, up and running now, testing will be done in this ticket: https://github.com/icgc-argo/kship/issues/3.

**Comment by blabadi** [comment]
PR to update kship in rdpc prod 
https://github.com/icgc-argo/rdpc-infra/pull/121/files
